################################################################################
###                                                                          ###
### Created by Alexandre Daby-Seesaram                                       ###
###                                                                          ###
### École Polytechnique, Palaiseau, France                                   ###
###                                                                          ###
################################################################################

project:
  resources:
    - "Resources/Documents"
    - "style_LMS.scss"
    - "style_LMS_dark.scss"
  type: website
  output-dir: public
website:
  title: "Pôle Méca seminar series"
  site-url: https://polemecanique.github.io/
  description: "Pôle Méca seminar series website"
  navbar:
    # logo: "Resources/Images/Logotype-X_ENSTA-Ecoles-Horizontal-Blanc.png"
    logo: "Resources/Images/Logotype_IPP_X_ENSTA.svg"
    right:
      - href: index.qmd
        text: Home
      - href: Schedule.qmd
        text: Schedule
      - href: Registration.qmd
        text: Register
      - href: PastSeminarsArchive.qmd
        text: Archive
      - href: AdditionalResources.qmd
        text: Miscellaneous

  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Next speaker** - The speaker on the 25th of April will be Daniel Papa from LadHyX! "
    type: light
    position: below-navbar

format:
  html:
    theme:
      light: [flatly,style_LMS.scss]
      dark: [darkly,style_LMS_dark.scss]
    css: styles.css
    toc: true



